artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/missile_data.zip
  unzip_dir: artifacts/data_ingestion
  s3_bucket_name: capstone-missile
  s3_object_key: missile_data.zip

Load_model:
  root_dir: artifacts
  pretrained_weights_path: artifacts/pretrained_weights/yolov8n.pt
  yaml_files_path: artifacts/yaml_data_files
  ultralytics_path: c:/Users/vishw/anaconda3/envs/capstone/Lib/site-packages/ultralytics


model_training:
  output_dir: missile_trained_weights
  runs_dir: runs/detect
  training_data_yaml: missile_data.yaml
  epochs: 3

model_validation:
  weights_path: missile_trained_weights/best.pt


