artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/missile_data.zip
  unzip_dir: artifacts/data_ingestion
  s3_bucket_name: capstone-missile
  s3_object_key: missile_data.zip
